name = "AsymptoticNumericalMethod"
uuid = "49cd1f3c-f820-4280-87fa-ee13bfe9a539"
authors = ["Romain Veltz <romain.veltz@inria.fr>"]
version = "0.1.0"

[deps]
BifurcationKit = "0f109fa4-8a5d-4b75-95aa-f515264e7665"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
TaylorIntegration = "92b13dbe-c966-51a2-8445-caca9f8a7d42"

[compat]
BifurcationKit = "0.3"
DocStringExtensions = "0.8.2, 0.8.3, 0.9"
ForwardDiff = "0.10"
Parameters = "0.12.3"
RecipesBase = "1.0, 1.1"
Setfield = "0.5.0, 0.7.0, 0.8.0, ^1.1"
TaylorIntegration = "0.14"
julia = "1.5"